export const miscTypes = {
  UPDATE_ERROR_MESSAGE: "UPDATE_ERROR_MESSAGE",
  UPDATE_EXER_TEXT: "UPDATE_EXER_TEXT",
  UPDATE_WORK_TEXT: "UPDATE_WORK_TEXT",
  CHANGE_HISTORY_PAGE: "CHANGE_HISTORY_PAGE"
};
