export const infoTypes = {
  GET_VIEW_EXERCISES: "GET_VIEW_EXERCISES",
  GET_EXERCISE_LIST: "GET_EXERCISE_LIST",
  GET_WORKOUT_LIST: "GET_WORKOUT_LIST",
  GET_WORKOUT_HISTORY: "GET_WORKOUT_HISTORY",
  ZERO_VIEW_WORKOUT: "ZERO_VIEWwORKOUT"
};
